# Generated by Django 5.1.1 on 2024-10-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mailinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='analysis_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
