# Generated by Django 5.1.1 on 2024-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdata',
            name='scrap_data',
            field=models.TextField(null=True),
        ),
    ]
