# Generated by Django 5.1.1 on 2024-10-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_apirequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='request_time',
            field=models.DateTimeField(),
        ),
    ]
